### ISSUE TITLE
function 

### ISSUE THREAD

**Issue by Timojl1** [nkming2/nc-photos#3]
Is it possible for you to add a "login" function?

So a function that asks for a password when you open the app before I can see your photos. Would be very happy. 

(I already bought the full version and I love the app, that's the only thing I'm missing at the moment)

**Comment by nkming2** [comment]
Hi, this feature is better provided by a 3rd party app-locker app instead of being built-in to this app as I believe it's out of the scope of a photos app. You should be able to find many on Play store.

\* This GitHub repo acts only as a mirror and I rarely monitor it, please visit the GitLab repo (https://gitlab.com/nkming2/nc-photos) for bug report/suggestions, thanks!

**Comment by nkming2** [comment]
I'm closing all issues and disabling the issue tracker here, if you have further questions please head to the GitLab repo instead, sorry for your inconvenience!
